_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "/gdrive/My Drive/checkpoints/sparsercnn.pth"
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_STD: [57.375, 57.120, 58.395]
  FPN:
    NORM: 'GN'
  ROI_BOX_HEAD:
    NORM: 'GN'
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001
  SparseRCNN:
    NUM_PROPOSALS: 10
    NUM_CLASSES: 22
TEST:
  EVAL_PERIOD: 250
  DETECTIONS_PER_IMAGE: 10
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 250
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.0032
  IMS_PER_BATCH: 12
  WARMUP_ITERS: 250
  RESET_ITER: False
  AMP:
    ENABLED: True
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "ClassAwareSampler"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  TRAIN_SIZE: 800
  TEST_SIZE: 800
  SCALE_RANGE: [0.9, 1]
  TEST_INPUT_TYPE: 'square'
OUTPUT_DIR: "/content/ckpt"
VERSION: 2
SEED: -1