_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_STD: [57.375, 57.120, 58.395]
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001
  SparseRCNN:
    NUM_PROPOSALS: 10
    NUM_CLASSES: 22
TEST:
  EVAL_PERIOD: 500
  DETECTIONS_PER_IMAGE: 10
SOLVER:
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 500
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.000025
  OPTIMIZER: "ADAMW"
  IMS_PER_BATCH: 6
  WARMUP_ITERS: 500
  RESET_ITER: False
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "ClassAwareSampler"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  TRAIN_SIZE: 800
  TEST_SIZE: 800
  SCALE_RANGE: [0.9, 1]
  TEST_INPUT_TYPE: 'square'
OUTPUT_DIR: "/content/ckpt"
VERSION: 2
