_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "/gdrive/My Drive/data/r101_300pro_3x_model.pth"
  RESNETS:
    SCALE: 4
    NUM_GROUPS: 9
    WIDTH_PER_GROUP: 27
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_STD: [57.375, 57.120, 58.395]
  ROI_BOX_HEAD:
    NORM: 'GN'
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001
  SparseRCNN:
    ACTIVATION: 'silu'
    NUM_PROPOSALS: 100
    NUM_CLASSES: 22
TEST:
  EVAL_PERIOD: 300
  DETECTIONS_PER_IMAGE: 100
SOLVER:
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 300
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.000025
  IMS_PER_BATCH: 8
  WARMUP_ITERS: 500
  RESET_ITER: True
  AMP:
    ENABLED: True
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "ClassAwareSampler"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  TRAIN_SIZE: 800
  TEST_SIZE: 800
  SCALE_RANGE: [0.9, 1]
  TEST_INPUT_TYPE: 'square'
OUTPUT_DIR: "/content/ckpt"
VERSION: 2
SEED: -1