_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_res2net_bifpn_backbone"
  BIFPN:
    NUM_BIFPN: 7
    OUT_CHANNELS: 288
  WEIGHTS: "/gdrive/My Drive/data/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.pth"
  RESNETS:
    DEPTH: 101
    WIDTH_PER_GROUP: 26
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.001
  SparseRCNN:
    NUM_PROPOSALS: 10
    NUM_CLASSES: 22
TEST:
  EVAL_PERIOD: 1000
  DETECTIONS_PER_IMAGE: 10
SOLVER:
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 1000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.002
  IMS_PER_BATCH: 3
  WARMUP_ITERS: 500
  RESET_ITER: True
DATALOADER:
  ASPECT_RATIO_GROUPING: False
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "ClassAwareSampler"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  MAX_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 800
  TRAIN_SIZE: 800
  TEST_SIZE: 800
  SCALE_RANGE: [0.9, 1]
  TEST_INPUT_TYPE: 'square'
OUTPUT_DIR: "/content/ckpt"
VERSION: 2
